export type { TablerIcon } from "@tabler/icons-react"
export {
  IconAlertCircle as AlertCircle,
  IconAlertTriangle as AlertTriangle,
  IconCheck as Check,
  IconChevronDown as ChevronDown,
  IconChevronLeft as ChevronLeft,
  IconChevronRight as ChevronRight,
  IconChevronUp as ChevronUp,
  IconDiscount as Discount,
  IconEdit as Edit,
  IconLayoutDashboard as LayoutDashboard,
  IconLoader2 as Loader,
  IconLogout as Logout,
  IconMenu2 as Burger,
  IconMoodPuzzled as MoodPuzzled,
  IconPlus as Plus,
  IconReceipt as Receipt,
  IconRestore as Restore,
  IconServerOff as ServerOff,
  IconSettings as Settings,
  IconToolsKitchen3 as ToolsKitchen,
  IconTrash as Trash,
  IconUser as User,
  IconUserCog as UserCog,
  IconX as X,
} from "@tabler/icons-react"
