/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appForbiddenRouteImport } from './routes/(app)/forbidden'
import { Route as appUsersRouteRouteImport } from './routes/(app)/users/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as appExampleIndexRouteImport } from './routes/(app)/example/index'
import { Route as appProfileIndexRouteImport } from './routes/(app)/profile/index'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appUsersIndexRouteImport } from './routes/(app)/users/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthRegisterCompleteRouteImport } from './routes/auth/register/complete'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appForbiddenRoute = appForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => appRouteRoute,
} as any)
const appUsersRouteRoute = appUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const appExampleIndexRoute = appExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appUsersIndexRoute = appUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appUsersRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterCompleteRoute = AuthRegisterCompleteRouteImport.update({
  id: '/auth/register/complete',
  path: '/auth/register/complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/users': typeof appUsersRouteRouteWithChildren
  '/forbidden': typeof appForbiddenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof appIndexRoute
  '/auth/register/complete': typeof AuthRegisterCompleteRoute
  '/example/': typeof appExampleIndexRoute
  '/profile/': typeof appProfileIndexRoute
  '/settings/': typeof appSettingsIndexRoute
  '/users/': typeof appUsersIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof appForbiddenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof appIndexRoute
  '/auth/register/complete': typeof AuthRegisterCompleteRoute
  '/example': typeof appExampleIndexRoute
  '/profile': typeof appProfileIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/users': typeof appUsersIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/users': typeof appUsersRouteRouteWithChildren
  '/(app)/forbidden': typeof appForbiddenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/(app)/': typeof appIndexRoute
  '/auth/register/complete': typeof AuthRegisterCompleteRoute
  '/(app)/example/': typeof appExampleIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(app)/users/': typeof appUsersIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/users'
    | '/forbidden'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/auth/register/complete'
    | '/example/'
    | '/profile/'
    | '/settings/'
    | '/users/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/auth/register/complete'
    | '/example'
    | '/profile'
    | '/settings'
    | '/users'
    | '/auth/register'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/users'
    | '/(app)/forbidden'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/(app)/'
    | '/auth/register/complete'
    | '/(app)/example/'
    | '/(app)/profile/'
    | '/(app)/settings/'
    | '/(app)/users/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthRegisterCompleteRoute: typeof AuthRegisterCompleteRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/forbidden': {
      id: '/(app)/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof appForbiddenRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/users': {
      id: '/(app)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof appUsersRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/example/': {
      id: '/(app)/example/'
      path: '/example'
      fullPath: '/example/'
      preLoaderRoute: typeof appExampleIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/users/': {
      id: '/(app)/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof appUsersIndexRouteImport
      parentRoute: typeof appUsersRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/complete': {
      id: '/auth/register/complete'
      path: '/auth/register/complete'
      fullPath: '/auth/register/complete'
      preLoaderRoute: typeof AuthRegisterCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appUsersRouteRouteChildren {
  appUsersIndexRoute: typeof appUsersIndexRoute
}

const appUsersRouteRouteChildren: appUsersRouteRouteChildren = {
  appUsersIndexRoute: appUsersIndexRoute,
}

const appUsersRouteRouteWithChildren = appUsersRouteRoute._addFileChildren(
  appUsersRouteRouteChildren,
)

interface appRouteRouteChildren {
  appUsersRouteRoute: typeof appUsersRouteRouteWithChildren
  appForbiddenRoute: typeof appForbiddenRoute
  appIndexRoute: typeof appIndexRoute
  appExampleIndexRoute: typeof appExampleIndexRoute
  appProfileIndexRoute: typeof appProfileIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appUsersRouteRoute: appUsersRouteRouteWithChildren,
  appForbiddenRoute: appForbiddenRoute,
  appIndexRoute: appIndexRoute,
  appExampleIndexRoute: appExampleIndexRoute,
  appProfileIndexRoute: appProfileIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthRegisterCompleteRoute: AuthRegisterCompleteRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
